### ISSUE TITLE
Compile in Arduino IDE 2.3.4 fails

### ISSUE THREAD

**Issue by Stefan4731** [marcinbor85/clip#1]
I'm new on Github, don't know if this is the correct place to leave a comment. Please forgive me if I'm wrong here and let me know where else I should send this.

I installed Clip 0.1.0 with Arduinos library manager, then I copied BasicCLI.ino, cli.c, sli.h from github in a new directory D:\BasicCLI. When I compile it with Arduino IDE 2.3.4 (CRTL-R) I get these errors:

```
D:\BasicCLI\cli.c:34:3: error: called object is not a function or function pointer
   34 |   CLIP_DEF_COMMAND_END_WITH_ARGS()
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from d:\sk008\Entwicklung\ESP32-C3\libraries\Clip\src/clip.h:34,
                 from D:\BasicCLI\cli.h:27,
                 from D:\BasicCLI\cli.c:25:
d:\sk008\Entwicklung\ESP32-C3\libraries\Clip\src/clip_defs.h:54:2: error: expected '}' before ';' token
   54 | };\
      |  ^~
   55 | 
      |   
D:\BasicCLI\cli.c:35:1: note: in expansion of macro 'CLIP_DEF_ROOT_COMMAND_END'
   35 | CLIP_DEF_ROOT_COMMAND_END()
      | ^~~~~~~~~~~~~~~~~~~~~~~~~
d:\sk008\Entwicklung\ESP32-C3\libraries\Clip\src/clip_defs.h:36:66: note: to match this '{'
   36 |     .args = (const struct clip_arg**)&(const struct clip_arg*[]) {\
      |                                                                  ^~
   37 | 
      |                                                                   
d:\sk008\Entwicklung\ESP32-C3\libraries\Clip\src/clip_defs.h:79:9: note: in expansion of macro '_CLIP_DEF_ARGUMENTS'
   79 |         _CLIP_DEF_ARGUMENTS()\
      |         ^~~~~~~~~~~~~~~~~~~
D:\BasicCLI\cli.c:28:67: note: in expansion of macro 'CLIP_DEF_WITH_ARGS'
   28 |   CLIP_DEF_COMMAND("get", "get pin state", cli_gpio_get_callback) CLIP_DEF_WITH_ARGS()
      |                                                                   ^~~~~~~~~~~~~~~~~~
D:\BasicCLI\BasicCLI.ino: In function 'void read_line(void (*)(char*))':
D:\BasicCLI\BasicCLI.ino:198:31: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]
  198 |         on_read_line(buf.c_str());
      |                      ~~~~~~~~~^~
      |                               |
      |                               const char*

exit status 1

Compilation error: called object is not a function or function pointer
```

**Comment by Stefan4731** [comment]
I digged a little deeper in the code:
1. In BasicCLI.ino line 198 it should be 
`on_read_line((char *)buf.c_str());` instead of `on_read_line(buf.c_str());`
2. `CLIP_DEF_COMMAND_END_WITH_ARGS()` does not exist. It should be replaced by `CLIP_DEF_COMMAND_END()`
3. The main clip handler should be the last entry after all command entries and not the first before them, otherwise you'll get build errors. In the cli.c source it is correct, but not in the README.md.

This eliminates all compile and build errors, but ... it does not do what it should do. Serial Monitor is showing the ">" prompt and then simply echoes everything I type in the message line. No functionality at all. `clip_cmd_parse_line(&g_cli_clip, NULL, line, NULL);` is doing nothing.
<img width="334" alt="Image" src="https://github.com/user-attachments/assets/41e92c6d-e836-4eed-886b-a504daab6d39" />

**Comment by Stefan4731** [comment]
Finally I got it. I had to replace 
```
void loop() {
  // async read line from Serial 
  read_line([](char *cmd_line) {
    // feed CLIP with command line
    clip_cmd_parse_line(&g_cli_clip, NULL, cmd_line, NULL);
  });  
}  
```
by
```
char line[128];
size_t lineLength;
void loop() {   
    line[0] = 0;
    lineLength = Serial.readBytesUntil('\n', line, 127);
    line[lineLength] = '\0';
    if(line[lineLength-1]==0x0d)
      line[lineLength-1] = '\0';
    if (line[0] != 0)
      clip_cmd_parse_line(&g_cli_clip, NULL, line, NULL);
}
```
I know, this is not state of the art, but it works. Works great now, thank you, Marcin!

**Comment by Stefan4731** [comment]
Update: the reason why 
```
void loop() {
  // async read line from Serial 
  read_line([](char *cmd_line) {
    // feed CLIP with command line
    clip_cmd_parse_line(&g_cli_clip, NULL, cmd_line, NULL);
  });  
}  
```
didn't work was a wrong setting in my Arduino serial monitor. It should be "New Line" instead of default "
No Line ending"
<img width="384" alt="Image" src="https://github.com/user-attachments/assets/dc5bf919-da1f-49bf-8436-888b63ebd257" />
So in the end these three issues should be fixed:
1. CLIP_DEF_COMMAND_END_WITH_ARGS() should be replaced by CLIP_DEF_COMMAND_END() in clip.c
2. The main clip handler should be the last entry after all command entries and not the first before them, otherwise you'll get build errors. In the cli.c source it is correct, but not in the README.md.
3. In BasicCLI.ino line 198 it should be on_read_line((char *)buf.c_str()); instead of on_read_line(buf.c_str()); 
Or change read_line() and loop() to:
```
void read_line(void (*on_read_line)(const char*)) {
  static String buf;
  char* ret = nullptr;
  if (Serial.available() > 0) {
    char ch = Serial.read();
    if (ch == '\n' || ch == '\r') {
      Serial.println();
      if (buf.length() != 0) {
        on_read_line(buf.c_str());  
        buf = "";
      }
      show_prompt();
    } else {
      Serial.print(ch);
      buf += ch;
    }
  }
}
void loop() {
  read_line([](const char *cmd_line) {
    char cmd_buffer[strlen(cmd_line) + 1]; 
    strcpy(cmd_buffer, cmd_line);          
    clip_cmd_parse_line(&g_cli_clip, NULL, cmd_buffer, NULL);
  });  
}
```
